kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llmops
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/llmops-cache
        containerPath: /root/.cache/huggingface
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8000
        protocol: TCP
      - containerPort: 30040
        hostPort: 4000
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
